services:
  db:
    image: postgres:17-alpine
    container_name: synapse-db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=synapse
    ports:
      - "5432:5432"
    volumes:
      - synapse-notes:/var/lib/postgresql/data

volumes:
  synapse-notes:
